#!/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config active_border_color  "#282A2E"
bspc config normal_border_color  "#282A2E"
bspc config focused_border_color "#E5989E"

bspc config ignore_ewmh_focus true
bspc rule -a steam desktop="4" state=floating center=true
bspc rule -a Spotify desktop="5" follow=off
spotify &
bspc rule -a discord desktop="6" follow=off
discord &
